# Generated by Django 4.1.3 on 2026-05-02 20:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='Código')),
                ('category', models.CharField(choices=[('HATCH', 'Hatch'), ('SEDAN', 'Sedan'), ('SUV', 'SUV')], max_length=100, verbose_name='Categoria do Automóvel')),
                ('model', models.CharField(max_length=200, verbose_name='Modelo')),
                ('model_year', models.IntegerField(blank=True, null=True, verbose_name='Ano do Modelo')),
                ('plate', models.CharField(blank=True, max_length=10, null=True, verbose_name='Placa')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('is_rented', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Automóvel',
                'verbose_name_plural': 'Automóveis',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=200, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='RegisterRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_start', models.DateTimeField(verbose_name='Início')),
                ('dt_end', models.DateTimeField(verbose_name='Fim')),
                ('create_at', models.DateField(blank=True, default=datetime.datetime.now)),
                ('automovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_rent', to='myapp.automovel')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Registrar Aluguel',
                'verbose_name_plural': 'Registrar Aluguéis',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AutomovelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images', verbose_name='Images')),
                ('automovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automovel_images', to='myapp.automovel')),
            ],
        ),
    ]
