name: DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # Vertente 1: Varredura de Segredos.
  secrets-scanning:
    name: TruffleHog Secrets Scan
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Run TruffleHog for Secrets Scanning
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./
        base: ""
        head: ""
        extra_args: --debug --only-verified

  # Vertente 2: Análise de Vulnerabilidades em Dependências.
  sca-trivy:
    name: Trivy Dependency Scan
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Varredura de Vulnerabilidades em Bibliotecas
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'table'
        exit-code: '1' # Trava o build se achar vulnerabilidades.
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'

  # Vertente 3: Análise Estática de Segurança.
  sast-codeql:
    name: CodeQL Static Analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write # Obrigatório para o robô ter permissão de publicar os alertas no painel do GitHub.

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: 'python' # Configuração para o ambiente Django do Carro Nômade.

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:python"

    